### PR TITLE
WordPress ESlint settings

### PR DESCRIPTION
**Pull request by junaidbhura**
### Description of the Change

This fixes: https://github.com/10up/eslint-config/issues/15

### Benefits

The WordPress JS coding standards have changed a lot, particularly after Gutenberg.

Using the recommended JS coding standards will bring development closer to what happens in core.

### Possible Drawbacks

1. Devs will have to get up to speed with the changes, and older projects will need to point to the older version of this config
1. I've referenced version `2.4.0` which is the last version before major [breaking changes](https://github.com/WordPress/gutenberg/blob/master/packages/eslint-plugin/CHANGELOG.md). We would need to keep an eye on what happens in core and carefully update it as needed

### Verification Process

Tested this by installing my fork locally and running `eslint test.js`. It picked up the correct coding standards.

`npm install https://github.com/junaidbhura/eslint-config#feature/wp-js-standards --save-dev`

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

Fixes: https://github.com/10up/eslint-config/issues/15
Fixes: https://github.com/10up/eslint-config/issues/6
Fixes: https://github.com/10up/eslint-config/issues/11

### CODE REVIEW

**Comment by nicholasio** [comment]
@jeffpaul Assigning this one to me.

@junaidbhura Thanks for the PR, I do agree that we need to update our JS eslint config but Gutenberg is not the only thing we write JavaScript for so I want to make sure we can have a eslint config that better support most of 10up's projects.

**Comment by junaidbhura** [comment]
Hey @nicholasio thanks! Yes, this works for all cases. Since we mostly now work with Webpack and ESNext on newer projects, this works quite well. I've used this on many projects in the past outside of 10up.

If this is merged in, I can also create pull requests on these repos to update it:

https://github.com/10up/theme-scaffold
https://github.com/10up/plugin-scaffold

What do you think?

**Comment by nicholasio** [comment]
@junaidbhura I think this is going to be a big change and we need to make sure we have enough documentation, best practices and discussion around this topic to better set up the team for success.

I do agree that the WordPress eslint config is good, but I also want to make sure our linting tools and best practices aren't limited by WordPress. For example, we should also be able to use this eslint config on non-WordPress projects and the wordpress-eslint-config package **might** not be a good fit for them. 

We might end up with an "opt-in" approach where teams would opt for a set of rules that makes the most sense for the project. I plan to spend some time on this next week and also start a bigger discussion to gather feedback from the team!

**Comment by junaidbhura** [comment]
Sounds good @nicholasio !

**Comment by nicholasio** [comment]
@junaidbhura Take a look at this and let me know your thoughts #17

**Comment by nicholasio** [comment]
Closing in favor #17

**Pull request closed without merging**
